#include <Arduino.h>
#include "Login.h"

String Login =
 "  <html>  "   
 "       <head>  "   
 "           <meta charset=\"utf-8\">  "   
 "           <meta name=\"viewport\" content=\"width=device-width, initial-scale=1, shrink-to-fit=no\">  "   
 "     "   
 "         "   
 "           <title>سیستم ابیاری هوشمند</title>  "   
 "     "   
 "     <style type=\"text/css\">  "   
 "     #test {  "   
 "     background-image: url(\"https://cdn.dribbble.com/users/1315300/screenshots/3556675/untitled-1.gif\");  "   
 "     width: 50%;  "   
 "       "   
 "     float: left;  "   
 "     background-attachment: fixed;}  "   
 "       .login_page{margin: auto; width: 70%; border: 1px solid rgb(0, 0, 0);overflow: auto;position: relative;border-radius: 50px;}  "   
 "       .login_col_left{background-color:#FFD700;width:50%;float:left;}  "   
 "       .login_col_right{background-color:#FFD700;width:50%;float:left;}  "   
 "       .login_col_rightb{  width:50%;float:left;}  "   
    
 "       body {font-family: \"Arial\";}  "   
 "       .login {margin: 50px auto;padding: 18px 20px;width: 200px;  "   
 "       background-clip: padding-box;}  "   
 "       .login > h1 {font-family: \"B Titr\";margin-bottom: 20px;font-size: 20px;font-weight: bold;color: rgb(221, 0, 0);text-align: center;text-shadow: 0 -1px rgba(0, 0, 0, 0.4);}  "   
 "       .login-input {display: block;width: 100%;height: 37px;margin-bottom: 20px; font-family: \"Arial\"; font-size: 26px; text-align: center; padding: 0 9px;color: white;text-shadow: 0 1px black;"   
 "       background: #2b3e5d;box-shadow: inset 0 1px 2px rgba(0, 0, 0, 0.3), 0 0 4px 1px rgba(255, 255, 255, 0.6);}  "   
 "       .login-submit {display: block;width: 100%;height: 37px;margin-bottom: 15px;font-size: font-family: \"Arial\"; 14px;  "   
 "       font-weight: bold;color: #294779;text-align: center;text-shadow: 0 1px rgba(255, 255, 255, 0.3);}  "   
 "     </style>  "   
 "     </head>  "   
 "     <body>  "   
 "           <div class=\"login_page\">  "   
 "               <div class=\"login_col_left\">  "   
 "                   <form method=\"POST\" class=\"login\">  "   
 "                   <h1>سیستم ابیاری هوشمند</h1>  "   
 "                   <input type=\"text\" name=\"USERNAME\" class=\"login-input\" placeholder=\"نام کاربری\">  "   
 "                   <input type=\"password\" name=\"PASSWORD\" class=\"login-input\" placeholder=\"رمز عبور\">  " 
 "                    <input type='submit' name='SUBMIT' value='ورود' class='login-submit'></form>"
   
 "     "   
 "                     "   
 "     "   
 "               </div>  "   
 "               <div class=\"login_col_rightb\">  "   
 "                       <img src=\"https://cdn.dribbble.com/users/1315300/screenshots/3556675/untitled-1.gif\" alt=\"Flowers in Chania\" style=\"display: block;margin-left: auto;margin-right: auto;width: 100%;\">  "   
 "     "   
 "     "   
 "               </div>  "   
 "           </div>  "   
 "           <h1 style=\"text-align: center\">طراحی و توسعه توسط اسماعیل جلالی و علی عزیزی</h1>  "  
 "           <h2 style=\"text-align: center\">ver : 0.2 - feb 2019</h1>  "   
 "     "   
 "                    "   
 "     "   
 "   </body>  "   
 "  </html>  " ; 
